### ISSUE TITLE
Deprecated warnings

### ISSUE THREAD

**Issue by EricdeWaal** [joomla-extensions/search#21]
### Steps to reproduce the issue
Use Search module in sidebar

### Expected result
A clean search field is shown

### Actual result
Above the search field, an error is shown:
Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /usr/www/users/prachta/dtc/modules/mod_search/mod_search.php on line 44

### System information (as much as possible)
Joomla! 4.2.4
PHP Version | 8.1.12
Error reporting: maximum

### Additional comments
Search does work

**Comment by chmst** [comment]
Is it a search module of the decoupled com_search or from the modern smart search?

Which Template? Can you check if ther is an override for the search module?

**Comment by EricdeWaal** [comment]
The template is Cassiopeia. There are no overrides. Smart Search is completely disabled.

**Comment by chmst** [comment]
modules/mod_search/mod_search.php on line 44

**Comment by EricdeWaal** [comment]
Please do, thank you!

**Comment by chmst** [comment]
Closing for PR #22
